### ISSUE TITLE
Check np.nan inside array

### ISSUE THREAD

**Issue by arnaldorusso** [pyoceans/python-oceans#10]
Hi @ocefpaf, 
How should be the properly way to check the existence of nans inside any of arrays used to compute variables?

I have found [match_args_return](https://github.com/pyoceans/python-oceans/blob/d64bc0f355f999c1ebd16a881588097b94d34871/oceans/utilities.py) but this do not do the job; or at least I did not find the desired results.

    from oceans.utilities import match_args_return
    a = np.array([0, 1, np.nan, 2, 3, np.nan])
    match_args_return(a)

returns an `AttributeError`:

          29         self.func = func
          30         self.__doc__ = func.__doc__
    ---> 31         self.__name__ = func.__name__
          32 
          33     def __call__(self, *args, **kw):
          AttributeError: 'numpy.ndarray' object has no attribute '__name__'

This kind of masking (where each of the function input arrays are masked based on other input) should be defined inside `python-oceans` or it's better let the users define it?

**Comment by ocefpaf** [comment]
> How should be the properly way to check the existence of nans inside any of arrays used to compute variables?

If all you want to do is to check for `nans` see `np.isnan()`.

`match_args_return` is designed to be a function decorator and not called as function.  From the docstring:
```python
    """Function decorator to homogenize input arguments and to make the output
    match the original input with respect to scalar versus array, and masked
    versus ndarray."""
```

  Here is an example:

```python
import numpy as np
import numpy.ma  as ma


def add_mean(arr):       
    return arr + arr.mean()

a = np.array([0, 1, np.nan, 2, 3, np.nan])
add_mean(a)

Out[1]: array([ nan,  nan,  nan,  nan,  nan,  nan])
```

Using match_args_return will make that function behave like the input is a masked array, but will return an object of the same type as the input (if masked will return masked).

```python
from oceans.utilities import match_args_return

@match_args_return
def add_mean(arr):       
    return arr + arr.mean()

a = np.array([0, 1, np.nan, 2, 3, np.nan])
add_mean(a)

Out[2]: array([ 1.5,  2.5,  nan,  3.5,  4.5,  nan])

add_mean(ma.masked_invalid(a))
Out[3]: 
masked_array(data = [1.5 2.5 -- 3.5 4.5 --],
             mask = [False False  True False False  True],
       fill_value = 1e+20)

masked_array(data = [2.0 3.0 -- 4.0 5.0 --],
             mask = [False False  True False False  True],
       fill_value = 1e+20)
```
