### ISSUE TITLE
Please check this line of code.

### ISSUE THREAD

**Issue by mfilipen** [pyoceans/python-oceans#63]
[Check this line of code.](https://github.com/pyoceans/python-oceans/blob/3dc98ceb84c9885c2433636d483794261afa4f43/oceans/sandbox/lines.py#L198)

3/2 = 1 not 1.5

**Comment by daf** [comment]
The behavior differs depending on Python 3 or 2:

```
~ => python2.7
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 3/2
1
```

```
~ => python
Python 3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:07:33)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 3/2
1.5
```

Should probably just update this line to be `3/2.`

**Comment by ocefpaf** [comment]
I'm actually removing support for 2.7 everywhere. I'm surprised I never added `future` imports here. Closing this b/c the right "fix" is to mention we no longer support Python 2.7.
