### ISSUE TITLE
Can't find the "seawater.py" routine ?

### ISSUE THREAD

**Issue by HugoDayan** [pyoceans/python-oceans#84]
Hello,

I can't find the subroutine "seawater.py", which is essential to calculate several parameters from the routine sea_extras.py.

Thank you in advance

Hugo D

**Comment by ocefpaf** [comment]
It is a separate package, see https://github.com/pyoceans/python-oceans/blob/master/requirements.txt#L5

How are you installing oceans? Both pip and conda handle the dependencies correctly.

**Comment by ocefpaf** [comment]
Closing this as solve. Please let us know if you are still struggling with this.
